[project]
name = "MediBlock"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/MediBlock/MediBlock/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.health-data-ledger]
path = "contracts/health-data-ledger.clar"

[contracts."secure-med-record.clar"]
path = "contracts/secure-med-record.clar.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
